language: ruby
cache: bundler
services:
  - mysql
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec
notifications:
    slack: topgun-hq:5npRXFbrSYuIgmYG1Y642esl
rvm:
  - 2.3.4
  - 2.4.1
