# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 406054abd4731e623063ecda28cbcaf66b94d2375893544c5b2107d14889d5dfcc3ef0af4f9561b79beb8261f9c3582ed44f8a0b0e795258b371981f38f23031

test:
  secret_key_base: ca506613a671b66ebe750818ff9db53977f3e1f480b81793eec5861ff6f294c8e537d153d409e66e06629087fce7afe35badcd5d2cd21522870272008ac9dae1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
